from typing import Any, Literal
from pydantic import BaseModel, Field


ActionType = Literal[
    "generate_analysis_summary",
    "prepare_recommendation",
    "create_structured_report_payload",
    "profile_dataset",
    "train_model",
]


class ActionRequest(BaseModel):
    """Abstraction for safe, controlled local operations within the assistant."""

    action_type: ActionType = Field(..., description="Type of safe demonstration action requested")
    description: str = Field(..., description="Human-readable explanation of the action")
    parameters: dict[str, Any] = Field(default_factory=dict, description="Action-specific parameters")
    requires_approval: bool = Field(default=False, description="True if action requires human confirmation")


class ActionResult(BaseModel):
    """Result payload emitted after executing a controlled action."""

    action_type: str = Field(..., description="Type of action executed")
    status: Literal["success", "failed", "pending_approval", "rejected"] = Field(..., description="Execution status")
    summary: str = Field(..., description="Concise summary of action execution outcome")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Metadata produced by action execution")


ReportType = Literal["dataset_analysis", "document_analysis", "image_analysis", "executive_summary"]


class ReportSection(BaseModel):
    """Structured section within a synthesized insight report."""

    title: str = Field(..., description="Section title")
    content: str = Field(..., description="Section narrative text")
    bullet_points: list[str] = Field(default_factory=list, description="Key key takeaways or bullet items")


class ReportPayload(BaseModel):
    """Structured report/insight model generated by the assistant."""

    report_type: ReportType = Field(..., description="Domain report classification")
    title: str = Field(..., description="Title of the report")
    summary: str = Field(..., description="Executive summary overview")
    sections: list[ReportSection] = Field(default_factory=list, description="Detailed report sections")
    metrics: dict[str, Any] = Field(default_factory=dict, description="Key numerical or evaluation metrics")
    citations: list[str] = Field(default_factory=list, description="Source citation labels")
    recommendations: list[str] = Field(default_factory=list, description="Actionable recommendations")
