from pydantic import BaseModel, Field
from poc_kanini.models.orchestration import ActivityEvent


class ImageAttachment(BaseModel):
    """An optional base64-encoded image attached to a chat request."""

    filename: str = Field(default="upload.png")
    mime_type: str = Field(default="image/jpeg", pattern="^image/(jpeg|png|webp)$")
    data: str = Field(min_length=1, description="Base64-encoded image bytes.")


class ChatMessage(BaseModel):
    """A validated browser/API message used to build LangGraph state."""

    role: str = Field(pattern="^(user|assistant)$")
    content: str = Field(min_length=1, max_length=20_000)


class ChatRequest(BaseModel):
    """Phase 8 chat request supporting messages, attachments, thread persistence, document association, and approval decisions."""

    messages: list[ChatMessage] = Field(min_length=1, max_length=40)
    attachments: list[ImageAttachment] = Field(default_factory=list, max_length=5)
    thread_id: str | None = Field(default=None, description="Optional thread/session identifier for checkpointed context")
    document_id: str | None = Field(default=None, description="Optional document ID associated with conversation")
    document_ids: list[str] = Field(default_factory=list, description="List of document IDs associated with conversation")
    approval: str | None = Field(default=None, pattern="^(approved|rejected)$", description="Human approval decision for interrupted operations")


class ChatResponse(BaseModel):
    """Phase 8 unified chat response returning message, thread_id, activities, citations, tool_results, reports, actions, and approval request."""

    message: ChatMessage
    thread_id: str = Field(description="Thread/session ID associated with the checkpointed state")
    approval_required: bool = Field(default=False, description="True if graph execution was interrupted awaiting human approval")
    approval_id: str | None = Field(default=None, description="Unique identifier for the approval request")
    approval_reason: str | None = Field(default=None, description="Human-readable explanation of why approval is required")
    activities: list[ActivityEvent] = Field(default_factory=list, description="Activities emitted during execution")
    citations: list[dict] = Field(default_factory=list, description="Citations generated during evidence retrieval")
    tool_results: list[dict] = Field(default_factory=list, description="Structured tool outputs emitted by specialist nodes")
    warnings: list[str] = Field(default_factory=list, description="Non-fatal warnings generated during execution")
    synthesis_status: str = Field(default="success", description="Whether Gemini synthesis succeeded, degraded, or was quota exhausted")
    reports: list[dict] = Field(default_factory=list, description="Structured insight reports generated by the assistant")
    actions: list[dict] = Field(default_factory=list, description="Safe controlled actions executed or requested")
